log_level: debug
http_server:
  host: localhost:8080
  key: key
  key_file: ./crypto/private.rsa
  trust_subnet: 192.168.5.0/24
file_storage:
  path: /tmp/metrics-db.json
  flush_interval: 10s
  restore: true
  use_file: false
database:
  dsn: postgres://practicum:yandex@localhost:5432/postgres?sslmode=disable
  use_pg: false
grpc_server:
  host: localhost:8081