server:
  log_level: debug
  host: localhost:8080
  key: key
  key_file: ./crypto/private.rsa
  trust_subnet: 0.0.0.0/16
file_storage:
  path: /tmp/metrics-db.json
  flush_interval: 10s
  restore: true
  use_file: false
database:
  dsn: postgres://practicum:yandex@localhost:5432/postgres?sslmode=disable
  use_pg: false
