POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
POST http://localhost:8080/update/counter/someMetric/53
###
POST http://localhost:8080/update/counter/anotherMetric/341
###
POST http://localhost:8080/update/gauge/gaugeMetric/78
###
POST http://localhost:8080/update/gauge/gaugeAnother/12.11109000
###
POST http://localhost:8080/update/gauge/gaugeAnother/14
###
POST http://localhost:8080/update/gauge/gaugeAnother/678
###
GET http://localhost:8080/value/counter/anotherMetric
###
GET http://localhost:8080/value/gauge/gaugeAnother
###
POST http://localhost:8080/update/gauge/gaugeAnother/none
###
GET http://localhost:8080/value/counter/someMetric
###
GET http://localhost:8080

