// Code generated by gowrap. DO NOT EDIT.
// template: ../../../../../templates/gowrap/zap
// gowrap: http://github.com/hexdigest/gowrap

package updatejson

//go:generate gowrap gen -p github.com/h2p2f/practicum-metrics/internal/server/httpserver/handlers/updatejson -i Updater -t ../../../../../templates/gowrap/zap -o updatejson_with_logging.go -l ""

import (
	"go.uber.org/zap"
)

// UpdaterWithZap implements Updater that is instrumented with zap logger
type UpdaterWithZap struct {
	_log  *zap.Logger
	_base Updater
}

// NewUpdaterWithZap instruments an implementation of the Updater with simple logging
func NewUpdaterWithZap(base Updater, log *zap.Logger) UpdaterWithZap {
	return UpdaterWithZap{
		_base: base,
		_log:  log,
	}
}

// GetCounter implements Updater
func (_d UpdaterWithZap) GetCounter(name string) (value int64, err error) {
	_d._log.Debug("UpdaterWithZap: calling GetCounter", zap.Reflect("params", map[string]interface{}{
		"name": name}))
	defer func() {
		if err != nil {
			_d._log.Error("UpdaterWithZap: method GetCounter returned an error", zap.Error(err))
		} else {
			_d._log.Debug("UpdaterWithZap: method GetCounter finished", zap.Reflect("results", map[string]interface{}{
				"value": value,
				"err":   err}))
		}
	}()
	return _d._base.GetCounter(name)
}

// GetGauge implements Updater
func (_d UpdaterWithZap) GetGauge(name string) (value float64, err error) {
	_d._log.Debug("UpdaterWithZap: calling GetGauge", zap.Reflect("params", map[string]interface{}{
		"name": name}))
	defer func() {
		if err != nil {
			_d._log.Error("UpdaterWithZap: method GetGauge returned an error", zap.Error(err))
		} else {
			_d._log.Debug("UpdaterWithZap: method GetGauge finished", zap.Reflect("results", map[string]interface{}{
				"value": value,
				"err":   err}))
		}
	}()
	return _d._base.GetGauge(name)
}

// SetCounter implements Updater
func (_d UpdaterWithZap) SetCounter(name string, value int64) {
	_d._log.Debug("UpdaterWithZap: calling SetCounter", zap.Reflect("params", map[string]interface{}{
		"name":  name,
		"value": value}))
	defer func() {
		_d._log.Debug("UpdaterWithZap: SetCounter finished")
	}()
	_d._base.SetCounter(name, value)
	return
}

// SetGauge implements Updater
func (_d UpdaterWithZap) SetGauge(name string, value float64) {
	_d._log.Debug("UpdaterWithZap: calling SetGauge", zap.Reflect("params", map[string]interface{}{
		"name":  name,
		"value": value}))
	defer func() {
		_d._log.Debug("UpdaterWithZap: SetGauge finished")
	}()
	_d._base.SetGauge(name, value)
	return
}
